name: ${name}
main: com.apocalypsjenl.openaudiomc.addon.plotsquared.PlotSquaredHook
version: ${version}
author: ${author}, together with the contributor(s) ${contributors}
depend: [PlotSquared, OpenAudioMc]

commands:
  music:
    desciption: Manage the music on your plot
    usage: /music