name: ${name}
main: com.apocalypsjenl.openaudiomc.addon.plotsquared.PlotSquaredHook
version: ${version}
author: ${author}
depend: [PlotSquared, OpenAudioMc]

commands:
  music:
    desciption: Manage the music on your plot
    usage: /music